name: Create-or-update-pact-webhook
description: 'This action creates/updated pact webhooks. can also be used for pact flow'
author: rajnavakoti
branding:
  icon: 'arrow-right'
  color: 'yellow'

inputs:
  # Webhook specifications
  action:
    description: Webhook action [Allowed - create, update]
    required: true
  webhook_type:
    description: Type of webhook [Allowed - trigger_provider_job, consumer_commit_status]
    required: true

  # Git repository details
  organization:
    description: Name of the organization
    required: true
  repository:
    description: Name of the repository
    required: true
  github_personal_access_token:
    description: git access token
    required: true
  description:
    description: Webhook description
    required: true

  # Broker authentication details [either token or username+password needed to be provided]
  broker_base_url:
    description: The base URL of the Pact Broker
    required: true
  broker_username:
    description: Pact Broker basic auth username
    required: false
  broker_password:
    description: Pact Broker basic auth password
    required: false
  broker_token:
    description: Pact Broker bearer token
    required: false
  user:
    description: Webhook basic auth username and password eg. username:password
    required: false

  # consumer details
  consumer:
    description: Consumer name
    required: false
  consumer_label:
    description: Consumer label, mutually exclusive with consumer name
    required: false

  # provider details
  provider:
    description: Provider name
    required: false
  provider_label:
    description: Provider label, mutually exclusive with provider name
    required: false

  # contract content changed flags [must be boolean - true or false]
  contract_content_changed:
    description: Trigger this webhook when the pact content changes
    required: false
  no_contract_content_changed:
    description: Trigger this webhook when the no pact content changes
    required: false

  # contract content flags [must be boolean - true or false]
  contract_published:
    description: Trigger this webhook when a pact is published
    required: false
  no_contract_published:
    description: Trigger this webhook when no contract published
    required: false

  # provider verification flags [must be boolean - true or false]
  provider_verification_published:
    description: Trigger this webhook when a provider verification result is published
    required: false
  no_provider_verification_published:
    description: Trigger this webhook when no provider verification result published
    required: false

  # failed provider verification results flags [must be boolean - true or false]
  provider_verification_failed:
    description: Trigger this webhook when a failed provider verification result is published
    required: false
  no_provider_verification_failed:
    description: Trigger this webhook when no failed provider verification result published
    required: false

  # success provider verification results flags [must be boolean - true or false]
  provider_verification_succeeded:
    description: Trigger this webhook when a successful provider verification result is published
    required: false
  no_provider_verification_succeeded:
    description: Trigger this webhook when no successful provider verification result published
    required: false

  # contract requires verification flags [must be boolean - true or false]
  contract_requiring_verification_published:
    description: Trigger this webhook when a contract is published that requires verification
    required: false
  no_contract_requiring_verification_published:
    description: Trigger this webhook when no contract is published that requires verification
    required: false

  # team uuid - only applicable for Pact flow
  team_uuid:
    description: UUID of the Pactflow team to which the webhook should be assigned (Pactflow only)
    required: false

outputs:
  webhook_uuid:
    description: UUID of created webhook

runs:
  using: 'docker'
  image: 'Dockerfile'
